name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  shamsi_date: ^1.0.4
  shared_preferences: 2.3.3
  flutter_local_notifications: ^18.0.1
  timezone: ^0.9.4
  device_calendar: ^4.3.3
  permission_handler: ^11.4.0
  image_picker: ^1.1.2
  file_picker: ^8.1.2
  path_provider: ^2.1.5
  url_launcher: ^6.3.1
  flutter_svg: ^2.0.10+1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

dependency_overrides:
  shared_preferences_android: 2.4.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/logo.webp
    - assets/intro/
    - icon-new.png
  fonts:
    - family: Vazirmatn
      fonts:
        - asset: assets/fonts/Vazirmatn-FD-Thin.ttf
          weight: 100
        - asset: assets/fonts/Vazirmatn-FD-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Vazirmatn-FD-Light.ttf
          weight: 300
        - asset: assets/fonts/Vazirmatn-FD-Regular.ttf
          weight: 400
        - asset: assets/fonts/Vazirmatn-FD-Medium.ttf
          weight: 500
        - asset: assets/fonts/Vazirmatn-FD-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Vazirmatn-FD-Bold.ttf
          weight: 700
        - asset: assets/fonts/Vazirmatn-FD-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Vazirmatn-FD-Black.ttf
          weight: 900

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "icon-new.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "icon-new.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "icon-new.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "icon-new.png"
